# Generated by Django 3.2.7 on 2021-11-28 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEntrada', models.DateField(help_text='Utilize o formato AAAA-MM-DD', verbose_name='Data de entrada')),
                ('dataSaida', models.DateField(help_text='Utilize o formato AAAA-MM-DD', verbose_name='Data de saída')),
                ('horarioEntrada', models.TimeField(help_text='Utilize o formato HH:MM', verbose_name='Horário de entrada')),
                ('horarioSaida', models.TimeField(help_text='Utilize o formato HH:MM', verbose_name='Horário de saída')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
