# Generated by Django 3.2.7 on 2021-11-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Insira seu nome', max_length=100)),
                ('email', models.EmailField(help_text='Insira seu e-mail', max_length=200)),
                ('dtNasc', models.DateField(help_text='Insira sua data de nascimento no formato DD/MM/AAAA', verbose_name='Data de nascimento')),
            ],
        ),
    ]
