# Generated by Django 3.2.7 on 2021-11-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0002_auto_20211120_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='horarioEntrada',
            field=models.TimeField(verbose_name='Data de entrada'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='horarioSaida',
            field=models.TimeField(verbose_name='Data de entrada'),
        ),
    ]
