# Generated by Django 3.2.7 on 2021-11-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0003_auto_20211120_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='horarioEntrada',
            field=models.TimeField(verbose_name='Horário de entrada'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='horarioSaida',
            field=models.TimeField(verbose_name='Horário de entrada'),
        ),
    ]
