# Generated by Django 3.2.7 on 2021-11-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0004_auto_20211120_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='horarioSaida',
            field=models.TimeField(verbose_name='Horário de saída'),
        ),
    ]
