# Generated by Django 3.2.7 on 2021-11-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0005_alter_reserva_horariosaida'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='nome',
            field=models.CharField(default='IdentificadorReserva', help_text='Atribua um nome identificador a sua reserva', max_length=100),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='dataEntrada',
            field=models.DateField(help_text='Utilize o formato AAAA-MM-DD', verbose_name='Data de entrada'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='dataSaida',
            field=models.DateField(help_text='Utilize o formato AAAA-MM-DD', verbose_name='Data de saída'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='horarioEntrada',
            field=models.TimeField(help_text='Utilize o formato HH:MM', verbose_name='Horário de entrada'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='horarioSaida',
            field=models.TimeField(help_text='Utilize o formato HH-MM', verbose_name='Horário de saída'),
        ),
    ]
