# Generated by Django 3.2.7 on 2021-11-28 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0006_auto_20211127_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='nome',
        ),
    ]
